# Generated by Django 3.1.1 on 2020-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200908_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUsernames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=254)),
            ],
        ),
    ]
