# Generated by Django 3.1.1 on 2020-09-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_like_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cameras'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations'),
        ),
    ]
